kind: Service
apiVersion: v1
metadata:
  name: my-web-service
spec:
  type: LoadBalancer
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web
      track: stable
  template:
    metadata:
      labels:
        app: my-web
        track: stable
    spec:
      containers:
      - name: my-web
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
